name: nanodev
version: 0.0.1
description: An experimental development environment.

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  codemirror: '>=0.1.4 <0.2.0'
  mime: any
  path: any

dev_dependencies:
  dart_to_js_script_rewriter: any
  ghpages_generator: any
  grinder: any
  unittest: any

transformers:
- dart_to_js_script_rewriter
