name: nanodev
version: 0.0.1
description: An experimental development environment.

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  codemirror: any
  mime: any
  path: any

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  grinder: any
  unittest: any

transformers:
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
