application: nanodev-824
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# re-direct to index.html if no path is give
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  login: admin

# access the static resources in the root directory
- url: /(.*)
  static_files: \1
  upload: (.*)
  secure: always
  login: admin
